services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    depends_on:
      - db
  db:
    image: postgres:16
    env_file: .env
    container_name: quest-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "5432:5432"

volumes:
  postgres_data:
