"""wallet_address add

Revision ID: 6a92be67492a
Revises: d83776ac789f
Create Date: 2024-07-07 19:31:37.152963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a92be67492a'
down_revision: Union[str, None] = 'd83776ac789f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wallet_address')
    # ### end Alembic commands ###
