"""add story_link

Revision ID: 9a9c805fd557
Revises: d9c257ec69d0
Create Date: 2024-08-27 15:56:57.268169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9c805fd557'
down_revision: Union[str, None] = 'd9c257ec69d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('story_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'story_link')
    # ### end Alembic commands ###
