"""first day persistence

Revision ID: ca6b1f646e2a
Revises: 9a9c805fd557
Create Date: 2024-08-27 18:56:50.906118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6b1f646e2a'
down_revision: Union[str, None] = '9a9c805fd557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passed_first_day', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('passed_second_day', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passed_second_day')
    op.drop_column('users', 'passed_first_day')
    # ### end Alembic commands ###
