from aiogram.fsm.state import StatesGroup, State


class QuestState(StatesGroup):
    FIRST_QUESTION_ASKED = State()
    FIRST_QUESTION_CHECKED = State()
    SECOND_QUESTION_ASKED = State()
    SECOND_QUESTION_CHECKED = State()
    THIRD_QUESTION_ASKED = State()
    FOURTH_QUESTION_ASKED = State()
    FIFTH_QUESTION_ASKED = State()
    SIXTH_QUESTION_ASKED = State()
    SEVENTH_QUESTION_ASKED = State()
    EIGHTH_QUESTION_ASKED = State()
    NINTH_QUESTION_ASKED = State()
    TENTH_QUESTION_ASKED = State()
    ELEVENTH_QUESTION_ASKED = State()
    ASKED_FOR_WALLET = State()
    ASKED_FOR_WALLET_CONFIRM = State()
    SAVED_LINK = State()
    ASKED_FOR_LINK = State()
    SAVE_WALLET = State()
    # ASKED_FOR_WALLET = State()
    HI = State()
    ALL_QUESTIONS_ANSWERED = State()
    FIRST_DAY_PASSED = State()
